spring.application.name=project-service

# Importation depuis le Config Server
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.fail-fast=false
spring.cloud.config.import-check.enabled=false
spring.cloud.config.profile=dev

server.port=${project-service.port}

# BD MySQL
spring.datasource.url=${project-service.datasource-url}
spring.datasource.username=${project-service.username}
spring.datasource.password=${project-service.password}

# JPA
spring.jpa.hibernate.ddl-auto=${project-service.hibernate-ddl-auto}
spring.jpa.show-sql=${project-service.show-sql}

# MongoDB (La nouveauté)
spring.mongodb.uri=${project-service.mongodb-uri}

# Eureka
eureka.client.service-url.defaultZone=${project-service.urlregistry}

# MAIL
spring.mail.host=${project-service.mail-host}
spring.mail.port=${project-service.mail-port}
spring.mail.username=${project-service.mail-username}
spring.mail.password=${project-service.mail-password}

# Accorder plus de temps au démarrage initial des appels inter-services
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000
resilience4j.timelimiter.instances.default.timeout-duration=8s